event:
  topics: topic1, topic2, topic3

  producers:
    - operationId: initialProducer
      topic: topic1
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      key: initialKey
      record:
        namespace: avro.example
        name: User
        value:
          name: user1
          age: 5
          notes:
            geography: 5
            maths: 7
          children:
            - name: Pepe
            - name: Germán

    - operationId: producer1
      topic: topic2
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      key: triggered-producer
      record:
        namespace: avro.example
        name: User
        ref: UserRef1

    - operationId: producer2
      topic: topic3
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      key: triggered-producer2
      record:
        namespace: avro.example
        name: User
        value:
          name: user2
          age: 69
          notes:
            geography: 3
            maths: 4
        children:
          - name: Genaro

  consumers:
    - operationId: consumer1
      topic: topic1
      delay: 3000
      launchOperationIds: [ producer1 ]
    - operationId: consumer2
      topic: topic2
      delay: 3000
      launchOperationIds: [ producer2 ]

  components:
    UserRef1:
      name: userRef1
      age: 5
      notes:
        geography: 5
        maths: 7
      children:
        - name: Gregoria
        - name: Guzmán
        - name: Pepita