spring:
  profiles:
    active: mock, mock-${MOCK_ENVIRONMENT}
  kafka:
    bootstrap-servers: localhost:29092
logging:
  level:
    org:
      apache:
        kafka: WARN
      springframework:
        kafka: WARN
    io:
      confluent:
        kafka: WARN